name: restart
channels:
  - tczhangzhi
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.3.2=h166bdaf_0
  - audioread=3.0.1=py39hf3d152e_2
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h19f5f5c_2
  - catkin_pkg=1.0.0=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - cftime=1.6.4=py39hf3d9206_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=8.2.1=h37d81fd_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_0
  - docutils=0.21.2=py39h06a4308_0
  - double-conversion=3.2.0=h9c3ff4c_0
  - eigen=3.4.0=h4bd325d_0
  - einops=0.8.0=pyhd8ed1ab_1
  - empy=3.3.4=pyh9f0ad1d_1
  - expat=2.6.4=h5888daf_0
  - ffmpeg=4.3.2=h37c90e5_3
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.55.3=py39h9399b63_0
  - freeglut=3.4.0=h6a678d5_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.10.0=pyhd8ed1ab_1
  - gcc=11.1.0=hee54495_1
  - gcc_impl_linux-64=11.1.0=h6b5115b_8
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h295c915_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.18.5=ha1a6a79_0
  - h5netcdf=1.4.1=pyhd8ed1ab_1
  - harfbuzz=3.1.1=h83ec7ef_0
  - hdf4=4.2.13=h10796ff_1005
  - hdf5=1.12.1=h70be1eb_2
  - icu=68.2=h9c3ff4c_0
  - imageio=2.36.1=pyh12aca89_1
  - imageio-ffmpeg=0.5.1=pyhd8ed1ab_1
  - importlib-resources=6.4.5=pyhd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jasper=2.0.33=h0ff4b12_1
  - jinja2=3.1.4=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - jsoncpp=1.9.5=h4bd325d_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.20.1=h568e23c_1
  - lame=3.100=h7b6447c_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=8_h3b12eaf_netlib
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=ha637b67_0
  - libcurl=8.2.1=h91b91d3_0
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=11.1.0=h80e7780_8
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - liblapacke=3.9.0=8_h3b12eaf_netlib
  - libllvm11=11.1.0=h9e868ea_6
  - libllvm14=14.0.6=hecde1de_4
  - libnetcdf=4.8.1=h424c3a0_4
  - libnghttp2=1.52.0=ha637b67_1
  - libogg=1.3.5=h4ab18f5_0
  - libopencv=4.5.5=py39h7d09d5f_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.19.6=he621ea3_0
  - librosa=0.9.2=pyhd8ed1ab_0
  - libsanitizer=11.1.0=h56837e0_8
  - libsndfile=1.2.2=hc60ed4a_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h5eee18b_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.4.0=h82bc61c_5
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h5cef20c_0
  - libzlib=1.2.13=h4ab18f5_6
  - lightning-utilities=0.11.9=pyhd8ed1ab_1
  - llvmlite=0.43.0=py39h6a678d5_0
  - loguru=0.7.2=py39hf3d152e_2
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib-base=3.9.4=py39h16632d1_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - mne-base=1.8.0=pyh694c41f_201
  - mne-connectivity=0.7.0=pyhd8ed1ab_0
  - moviepy=1.0.3=pyhd8ed1ab_1
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.0=py39h74842e3_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.24=he378463_2
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.4=h6a678d5_0
  - netcdf4=1.6.2=py39h89d13dc_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2=pyhd8ed1ab_0
  - nspr=4.36=h5888daf_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.60.0=py39h0320e7d_0
  - opencv=4.5.5=py39hf3d152e_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openldap=2.5.5=h2aa78c0_1
  - openssl=1.1.1w=h7f8727e_0
  - pandas=2.2.3=py39h3b40f6f_1
  - pcre2=10.42=hebb0a14_1
  - pillow=11.0.0=py39hfdbf927_0
  - pip=24.2=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pooch=1.8.2=pyhd8ed1ab_1
  - proglog=0.1.10=pyhaa61c55_0
  - proj=8.2.1=ha227179_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.11.4=h295c915_1
  - py-opencv=4.5.5=py39hef51801_0
  - pycparser=2.22=pyh29332c3_1
  - pyg=2.1.0=py39_torch_1.11.0_cu113
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pysocks=1.7.1=py39h06a4308_0
  - pysoundfile=0.12.1=pyhd8ed1ab_3
  - python=3.9.18=h7a1cb2a_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-lmdb=1.5.1=py39hcca4d6b_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.9=2_cp39
  - pytorch-cluster=1.6.0=py39_torch_1.11.0_cu113
  - pytorch-lightning=2.0.9=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py39_torch_1.11.0_cu113
  - pytorch-sparse=0.6.15=py39_torch_1.11.0_cu113
  - pytz=2024.1=pyhd8ed1ab_0
  - pyvista=0.44.2=pyhd8ed1ab_1
  - pyvistaqt=0.11.1=pyhdecd6ff_1
  - pywavelets=1.6.0=py39hd92a3bb_0
  - pyyaml=6.0.2=py39h8cd3c5a_1
  - qhull=2020.2=h4bd325d_2
  - qt=5.12.9=h9d6b050_2
  - qtpy=2.4.2=pyhdecd6ff_0
  - readline=8.2=h5eee18b_0
  - resampy=0.4.3=pyhd8ed1ab_0
  - rosdep=0.25.1=pyhd8ed1ab_0
  - rosdistro=1.0.1=pyhd8ed1ab_0
  - rospkg=1.5.1=pyhd8ed1ab_0
  - scikit-learn=1.6.0=py39h4b7350c_0
  - scooby=0.10.0=pyhd8ed1ab_1
  - seaborn=0.13.2=py39h06a4308_0
  - sip=6.5.1=py39he80948d_2
  - six=1.17.0=pyhd8ed1ab_0
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.5.0.post1=py39hf88036b_1
  - spectrum=0.8.1=py39hd1e30aa_3
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h4a8ded7_18
  - tbb=2021.8.0=hdb19cb5_0
  - tbb-devel=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd8ed1ab_1
  - torcheeg=1.1.2=py_0
  - torchmetrics=1.5.2=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h8cd3c5a_1
  - utfcpp=3.2.5=ha770c72_0
  - vtk=9.1.0=qt_py39h7d03e14_205
  - x264=1!161.3030=h7f98852_1
  - xarray=2023.7.0=pyhd8ed1ab_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==2.3.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - crypto==1.4.1
      - facenet-pytorch==2.6.0
      - fer==22.5.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.73.0
      - h5py==3.14.0
      - hf-xet==1.1.3
      - hidapi==0.14.0.post4
      - huggingface-hub==0.33.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - keras==3.10.0
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mediapipe==0.10.18
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - naked==0.1.32
      - namex==0.1.0
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.16.0
      - packaging==25.0
      - protobuf==5.29.5
      - pycryptodome==3.23.0
      - pygments==2.19.1
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - safetensors==0.5.3
      - scipy==1.8.1
      - sentencepiece==0.2.0
      - setuptools==80.9.0
      - shellescape==3.8.1
      - sounddevice==0.5.2
      - speechrecognition==3.14.3
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - tf-keras==2.19.0
      - tokenizers==0.21.1
      - torch==2.2.1+cu118
      - torchaudio==2.2.1+cu118
      - torchvision==0.17.1+cu118
      - transformers==4.51.3
      - triton==2.2.0
      - typing-extensions==4.14.0
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wheel==0.45.1
      - wrapt==1.17.2
      - zipp==3.23.0
